name: zhisuan11core
version: '1.0-SNAPSHOT'
main: org.zhisuan11.zhisuan11core.Zhisuan11core
api-version: '1.20'
authors: [RunicDolphin806]
commands:
  #插件指令名  /zhisuan11 ……
  zhisuan11:
    description: "欢迎指令"
    permission: Zhisuan11.Main
    aliases: zs
  tp:
    description: "传送指令"
    permission: Zhisuan11.tp
